#!/usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\DriverManager;

$db = [
        'dbname'   => 'seeder',
        'user'     => 'root',
        'password' => 'webdevel',
        'host'     => 'localhost',
        'driver'   => 'pdo_mysql',
    ];

$config = new Configuration();
$conn   = DriverManager::getConnection($db, $config);
$app    = new Application();

$container['db'] = $conn;

$app->addCommands([
        new Groovey\Seeder\Commands\About(),
        new Groovey\Seeder\Commands\Init($container),
        new Groovey\Seeder\Commands\Create($container),
        new Groovey\Seeder\Commands\Run($container),
    ]);

$status = $app->run();

exit($status);
